### ISSUE TITLE
Laravel 9 da ishlamayapti

### ISSUE THREAD

**Issue by diyorbektj** [sobirjonovs/laravel-rabbit#1]
Bu package laravel 9 da ishlatib bulmayapti iltimos shuni xal qilib bering

**Comment by sobirjonovs** [comment]
Assalomu alaykum, qanday xatolik chiqyapti?

**Comment by sobirjonovs** [comment]
> Bu package laravel 9 da ishlatib bulmayapti iltimos shuni xal qilib bering

Assalomu alaykum, qanday xatolik chiqyapti?

**Comment by diyorbektj** [comment]
> > Bu package laravel 9 da ishlatib bulmayapti iltimos shuni xal qilib bering
> 
> Assalomu alaykum, qanday xatolik chiqyapti?

 Problem 1
    - Root composer.json requires sobirjonovs/laravel-rabbit ^2.3 -> satisfiable by sobirjonovs/laravel-rabbit[2.3.0, ..., 2.3.5].
    - sobirjonovs/laravel-rabbit[2.3.0, ..., 2.3.5] require illuminate/support ~8 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

shunday deyapti

**Comment by sobirjonovs** [comment]
> > > Bu package laravel 9 da ishlatib bulmayapti iltimos shuni xal qilib bering
> > 
> > 
> > Assalomu alaykum, qanday xatolik chiqyapti?
> 
> Problem 1 - Root composer.json requires sobirjonovs/laravel-rabbit ^2.3 -> satisfiable by sobirjonovs/laravel-rabbit[2.3.0, ..., 2.3.5]. - sobirjonovs/laravel-rabbit[2.3.0, ..., 2.3.5] require illuminate/support ~8 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
> 
> shunday deyapti

Muammo haqida xabar berganingiz uchun rahmat. Packagega kiritilgan tuzatishlar v2.3.6 versiya bilan versiyalandi. Kompozer orqali packageni proyektingizga qaytadan o'rnatib ko'ring. Ishlaydi.
