### ISSUE TITLE
Message is hanging on while RPC request

### ISSUE THREAD

**Issue by sobirjonovs** [sobirjonovs/laravel-rabbit#10]
## **Description**
If you send a message via RPC queue, the RabbitMQ PHP Client processes it but doesn't give an acknowledgement, because it is hanging on a whatever way. Then, every message has been sent to that queue leads to freezing the system causing 504 bad gateway. 

## **Reproduce**
It can't be reproduced. I couldn't handle it. Only have guessing that it is because of the database timeout. Laravel somehow does not close the database connection and it leads to make the RabbitMQ Client freeze. 

## **Solutions**
1. Using a DB::reconnect() here when  the error occurs.
<img width="770" alt="image" src="https://github.com/sobirjonovs/laravel-rabbit/assets/51774058/db54025b-ac8e-4bbd-9d86-674494063529">
2. Checking if the message is consumed correctly, if it doesn't, it should be requeued by that queue which consumed the message.

I'm looking forward to get the write solutions! Thank you!

**Comment by usmonaliyev99** [comment]
i have not used waitRpc function but i will use it. Then i try to solve it.

**Comment by usmonaliyev99** [comment]
I am sorry bro, i cannot make error with waitRpc function. May you send me some example ?

**Comment by sobirjonovs** [comment]
> I am sorry bro, i cannot make error with waitRpc function. May you send me some example ?

That's the problem :) It is not happening every time. I couldn't track the error.

**Comment by usmonaliyev99** [comment]
Let's send me an example code to test.
You told me the database connection so I could not realize. If I see the sample code then I may understand the problem

**Comment by sobirjonovs** [comment]
I meant that sending a request from A service via rpc queue to the B service which receives the request and processes it and performs some database related operations.

**Comment by usmonaliyev99** [comment]
I am sorry bro, i even cannot use waitRpc function. There are nothing about waitRpc function in README.md so i don't know what am i doing. If you help me to create an error, i hope i will fix it

**Comment by sobirjonovs** [comment]
I will write if the error occurs, ok?
