### ISSUE TITLE
If DTO does not accept all keys of only function from queue, does DTO need to throw validation error ?

### ISSUE THREAD

**Issue by usmonaliyev99** [sobirjonovs/laravel-rabbit#12]

**Comment by usmonaliyev99** [comment]
if the message cannot pass validation, in rpc message will be returned with errors. But in subscriber and publisher mode sometime developer needs that message or does not need.

i offer let's add invalid_message_queue to config. It will be null and somebody set name of queue to it.

if it is null, application delete invalid message.
if it is not null, application publish this message with validation errors to other queue.

**Comment by sobirjonovs** [comment]
that's good, let's do it.
