### ISSUE TITLE
Install qilishda xatolik

### ISSUE THREAD

**Issue by salawatbro** [sobirjonovs/laravel-rabbit#15]
packageni install qildi, lekin srazu su xatolik beriyapti. provider ni publish qilishda.

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException 

  Unresolvable dependency resolving [Parameter #0 [ <required> $host ]] in class PhpAmqpLib\Connection\AMQPStreamConnection

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1141
    1137▕     protected function unresolvablePrimitive(ReflectionParameter $parameter)
    1138▕     {
    1139▕         $message = "Unresolvable dependency resolving [$parameter] in class {$parameter->getDeclaringClass()->getName()}";
    1140▕ 
  ➜ 1141▕         throw new BindingResolutionException($message);
    1142▕     }
    1143▕ 
    1144▕     /**
    1145▕      * Register a new before resolving callback for all types.

      +28 vendor frames 

  29  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by sobirjonovs** [comment]
Assalomu alaykum, configlarni merge qilmagansiz.

`php artisan vendor:publish --tag=rabbit-configs`

va 

`php artisan vendor:publish --tag=rabbit-providers `

komandalarini yozib, qayta urinib ko'ring.

**Comment by salawatbro** [comment]
Foydasi bolmadi, shu error chiqaybdi bari bir(

```
joldasbaevsalawat@Joldasbaevs-MacBook-Pro user % php artisan vendor:publish --tag=rabbit-configs

   Illuminate\Contracts\Container\BindingResolutionException 

  Unresolvable dependency resolving [Parameter #0 [ <required> $host ]] in class PhpAmqpLib\Connection\AMQPStreamConnection

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1141
    1137▕     protected function unresolvablePrimitive(ReflectionParameter $parameter)
    1138▕     {
    1139▕         $message = "Unresolvable dependency resolving [$parameter] in class {$parameter->getDeclaringClass()->getName()}";
    1140▕ 
  ➜ 1141▕         throw new BindingResolutionException($message);
    1142▕     }
    1143▕ 
    1144▕     /**
    1145▕      * Register a new before resolving callback for all types.

      +28 vendor frames 

  29  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

**Comment by usmonaliyev99** [comment]
Menda ham shunday bo'lardi, faqat men composer update qilganimda. Yani .env fayda AMQP_HOST ni yatagan bo'lsam.

.env faylga AMQP_HOST va qolgan o'zgaruvchilarni sozlab, qaytagan urinib ko'ringchi.

Boshqa tahmin:
app.php dagi providers ro'yxatiga RabbitServiceProvider.php qo'shilmagan bo'lishi mumkin.

**Comment by salawatbro** [comment]
Yangi loyiha create qilib yana shu packageni install qildim lekin, hali ham error chiqyapti. xato mendan mi shunda?

**Comment by usmonaliyev99** [comment]
RabbitServiceProvider.php ni app.php dagi providers ro'yxatiga qo'shdingizmi ?

**Comment by salawatbro** [comment]
@Temur5319436 
packagni install qilib bolib composerning commandlari ishga tushadi ku, birinchi bolib
"@php artisan package:discover --ansi" mana shu command ishga tushadi shuning ozida error beriyapti, install qilish toliq yakunlanmay turub shunaqa bolmoqda

"composer require sobirjonovs/laravel-rabbit" mana shu commandni terminalga berganda error beriyapi, unnan nariga otmayapti)

**Comment by usmonaliyev99** [comment]
Tushuindim, To'g'irlashga harakat qilib ko'raman

**Comment by usmonaliyev99** [comment]
> @Temur5319436 
> packagni install qilib bolib composerning commandlari ishga tushadi ku, birinchi bolib
> "@php artisan package:discover --ansi" mana shu command ishga tushadi shuning ozida error beriyapti, install qilish toliq yakunlanmay turub shunaqa bolmoqda
> 
> "composer require sobirjonovs/laravel-rabbit" mana shu commandni terminalga berganda error beriyapi, unnan nariga otmayapti)

Ok

**Comment by usmonaliyev99** [comment]
> @Temur5319436 packagni install qilib bolib composerning commandlari ishga tushadi ku, birinchi bolib "@php artisan package:discover --ansi" mana shu command ishga tushadi shuning ozida error beriyapti, install qilish toliq yakunlanmay turub shunaqa bolmoqda
> 
> "composer require sobirjonovs/laravel-rabbit" mana shu commandni terminalga berganda error beriyapi, unnan nariga otmayapti)

Bu xatolikni nimadan ekanligini topildi va to'g'irlandi, merge requestni yaratib qo'dim, Sanjar aka ko'rib chiqib, qo'shib, yangi versiya chiqarishsa. Nasib qilsa hammasi yaxshi bo'ladi.

**Comment by sobirjonovs** [comment]
Siz packageni dev-master versiyasini o'rnating. Hozirgi bizda bo'layotgan oxirigi o'zgarishlarni siz ololasiz. Shunda xatolar to'g'rilangan variantini tekshirib ko'rolasiz

@SalawatJoldasbaev

**Comment by salawatbro** [comment]
Ishladi rahmat bro

@Temur5319436 
@sobirjonovs
