### ISSUE TITLE
AMQP_HOST'ning default qiymatini o'zgartirish.

### ISSUE THREAD

**Issue by usmonaliyev99** [sobirjonovs/laravel-rabbit#18]
`src/config/amqp.php`
```php
<?php

return [
    'host' => env('AMQP_HOST', 'host.docker.internal'),
    'port' => env('AMQP_PORT', 5672),
    'username' => env('AMQP_USER', 'guest'),
    'password' => env('AMQP_PASSWORD', 'guest'),
    ...

```

`'host.docker.internal'` => `'127.0.0.1'`
Shu fikirga qanday qaraysiz ?

**Comment by sobirjonovs** [comment]
Yaxshi, o'zgartiring. U narsa doker ichidan bo'lganda yoziladigan adres. Ko'pincha 127.0.0.1 bo'ladi. 127 bo'laversin

**Comment by sobirjonovs** [comment]
O'zim o'zgartirdim hozir vaqtim bo'lgandi.
