### ISSUE TITLE
New install command

### ISSUE THREAD

**Issue by usmonaliyev99** [sobirjonovs/laravel-rabbit#19]
Let's add a new command which adds RabbitServiceProvider.php to the providers list of app.php.

It will be published like Laravel/telescope.

It may be:
php artisan rabbit:install

**Comment by usmonaliyev99** [comment]
It will run:
php artisan vendor:publish --tag=rabbit-configs
php artisan vendor:publish --tag=rabbit-providers

**Comment by sobirjonovs** [comment]
That's a good idea!!

**Comment by usmonaliyev99** [comment]
I am going to do it

**Comment by sobirjonovs** [comment]
Thank you, If you face any troubles, we can discuss it here.
