### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by usmonaliyev99** [sobirjonovs/laravel-rabbit#21]
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException 

  Unresolvable dependency resolving [Parameter #0 [ <required> $host ]] in class PhpAmqpLib\Connection\AMQPStreamConnection

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1141
    1137▕     protected function unresolvablePrimitive(ReflectionParameter $parameter)
    1138▕     {
    1139▕         $message = "Unresolvable dependency resolving [$parameter] in class {$parameter->getDeclaringClass()->getName()}";
    1140▕ 
  ➜ 1141▕         throw new BindingResolutionException($message);
    1142▕     }

**Comment by usmonaliyev99** [comment]
The error is still here, i try to find solution. But it will be big

**Comment by sobirjonovs** [comment]
Hi, lets solve it. It is a big issue. Why does it happen?

**Comment by usmonaliyev99** [comment]
When we create instance of  AMQPConnection, It try to connect to RabbitMq server. That is why the error is happening.

There are instance of AMQPConnection in RabbitServiceProvider.php.
That mean we don't need create instance of AMQPConnection in RabbitServiceProvider.php.
