### ISSUE TITLE
"composer install" command tries to connect to RabbitMQ server automatically

### ISSUE THREAD

**Issue by asrorbek-mannonov** [sobirjonovs/laravel-rabbit#23]
## Problem
While building a docker image from my Laravel project. I encountered the following problem:

```

  stream_socket_client(): Unable to connect to tcp://host.docker.internal:567
  2 (php_network_getaddresses: getaddrinfo for host.docker.internal failed: N
  ame does not resolve)

```

It looks like the `composer install` command automatically tries to connect the RabbitMQ server. 

## System info

Base Docker image: alpine:3.19
Docker host system: Ubuntu 22.04.3 LTS
Php version: php8.2
Composer version: 2.3.5

**Comment by usmonaliyev99** [comment]
> ## Problem
> 
> While building a docker image from my Laravel project. I encountered the following problem:
> 
> ```
> 
>   stream_socket_client(): Unable to connect to tcp://host.docker.internal:567
>   2 (php_network_getaddresses: getaddrinfo for host.docker.internal failed: N
>   ame does not resolve)
> ```
> 
> It looks like the `composer install` command automatically tries to connect the RabbitMQ server.
> ## System info
> 
> Base Docker image: alpine:3.19 Docker host system: Ubuntu 22.04.3 LTS Php version: php8.2 Composer version: 2.3.5

Check out https://packagist.org/packages/usmonaliyev/laravel-rabbit

**Comment by sobirjonovs** [comment]
> > ## Problem
> > 
> > While building a docker image from my Laravel project. I encountered the following problem:
> > 
> > ```
> > 
> >   stream_socket_client(): Unable to connect to tcp://host.docker.internal:567
> >   2 (php_network_getaddresses: getaddrinfo for host.docker.internal failed: N
> >   ame does not resolve)
> > ```
> > 
> > It looks like the `composer install` command automatically tries to connect the RabbitMQ server.
> > ## System info
> > 
> > Base Docker image: alpine:3.19 Docker host system: Ubuntu 22.04.3 LTS Php version: php8.2 Composer version: 2.3.5
> 
> Check out https://packagist.org/packages/usmonaliyev/laravel-rabbit

Hi bro, what is that?

**Comment by usmonaliyev99** [comment]
Assalomu alaykum!

Pull requestni qo'shmaganingizdan keyin, yangi composer package yaratishga majbur bo'ldim.

Shu o'zgarishlar qo'shilgan package, hozir 5-6 ta projectda ishlayapti.

**Comment by sobirjonovs** [comment]
> Assalomu alaykum!
> 
> Pull requestni qo'shmaganingizdan keyin, yangi composer package yaratishga majbur bo'ldim.
> 
> Shu o'zgarishlar qo'shilgan package, hozir 5-6 ta projectda ishlayapti.

Pull requestlarni ko'rmabman. Men anchadan beri faol emas edim uzr.

**Comment by sobirjonovs** [comment]
> ## Problem
> While building a docker image from my Laravel project. I encountered the following problem:
> 
> ```
> 
>   stream_socket_client(): Unable to connect to tcp://host.docker.internal:567
>   2 (php_network_getaddresses: getaddrinfo for host.docker.internal failed: N
>   ame does not resolve)
> 
> ```
> 
> It looks like the `composer install` command automatically tries to connect the RabbitMQ server. 
> 
> ## System info
> 
> Base Docker image: alpine:3.19
> Docker host system: Ubuntu 22.04.3 LTS
> Php version: php8.2
> Composer version: 2.3.5
> 
> 

Assalomu alaykum. Tekshirib ko'ringchi?
