### ISSUE TITLE
Do you need this info logs ?

### ISSUE THREAD

**Issue by usmonaliyev99** [sobirjonovs/laravel-rabbit#4]
![image](https://github.com/sobirjonovs/laravel-rabbit/assets/63544323/5a199cef-4e2f-4110-98b6-5bddbba03afa)

**Comment by sobirjonovs** [comment]
Hi. Yeah, it is useful for debugging purposes. But there is a minor issue: I should do it on another branch called devmaster. But, I'm an enough lazy for that :)

**Comment by usmonaliyev99** [comment]
if you accept my help, i can do it.

**Comment by sobirjonovs** [comment]
Okay :)
