### ISSUE TITLE
Let's change $client which is Client instance instead of the $this variable.

### ISSUE THREAD

**Issue by usmonaliyev99** [sobirjonovs/laravel-rabbit#7]
What do you think ?

![Screenshot from 2023-10-29 14-55-39](https://github.com/sobirjonovs/laravel-rabbit/assets/63544323/c0e6da64-5e7f-4c54-8de1-8904e8bc7002)

**Comment by usmonaliyev99** [comment]
$this->dispatchEvents($message); to $client->dispatchEvents($message);

**Comment by sobirjonovs** [comment]
Yeah, it is a good idea because there is used a closure which is in the same scope of the Client class.

**Comment by usmonaliyev99** [comment]
May I change it ?

**Comment by sobirjonovs** [comment]
Yes

**Comment by sobirjonovs** [comment]
Bro, I'm sorry I was confused. It is related to other functionals. It breaks the logics. I've used it so that I can use the client instance without "use" in the function block. We can't merge into codebase

**Comment by sobirjonovs** [comment]
Thank you for the issue!

**Comment by usmonaliyev99** [comment]
OK
